#!/bin/bash

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish infinispan cluster information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_publish_infinispan_cluster
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

CART_NS=$(get_cartridge_namespace_from_path)

source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_${CART_NS}_CLUSTER_PROXY_PORT
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_GEAR_DNS

OPENSHIFT_INFINISPAN_CLUSTER_PROXY_PORT=$(get_env_var_dynamic "OPENSHIFT_${CART_NS}_CLUSTER_PROXY_PORT")

echo ${OPENSHIFT_GEAR_DNS}:${OPENSHIFT_INFINISPAN_CLUSTER_PROXY_PORT}

