#!/bin/bash

# Publishes the infinispan connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish infinispan connection information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_infinispan_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/openshift/node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

echo -n "OPENSHIFT_INFINISPAN_HOST=$OPENSHIFT_INFINISPAN_HOST; "
echo -n "OPENSHIFT_INFINISPAN_PORT=$OPENSHIFT_INFINISPAN_PORT; "
echo ""
