#!/bin/bash

# Destroys infinispan instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_infinispan_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="infinispan-5.2"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3


$CART_INFO_DIR/hooks/conceal-port "$application" "$namespace" "$uuid"

if [ ! -d "$APP_HOME/app-root" ]
then
    echo "${application}.  Application directory doesn't exist:  $APP_HOME/app-root"
else
  disable_cgroups

  # Import env vars so they can be used:
  import_env_vars

  destroy_git_repo $application $uuid

  infinispan_pid=`jps -lmv | grep ".*infinispan.*${OPENSHIFT_INTERNAL_IP}.*" | awk {"print $1"} 2> /dev/null`

  stop_app

  force_kill $infinispan_pid

  rm_cartridge_instance_dir "$cartridge_type"

  enable_cgroups
fi

$CART_INFO_DIR/hooks/pre-destroy "$@"
